### ISSUE TITLE
Include songs subfolder in the VGM file path.

### ISSUE THREAD

**Issue by shoulderrats** [dtremblay/c256-vgm-player#1]
I found a super tiny fix for the vgm-player.asm file. It just needs the path to the "songs" subfolder included. :)

diff --git a/vgm-player.asm b/vgm-player.asm
index 9d67299..a2c76e3 100644
--- a/vgm-player.asm
+++ b/vgm-player.asm
@@ -513,5 +513,5 @@ VGM_FILE
 ;.binary "01 Title-ym2612.vgm"

 ; YM262
-.binary "02 At Doom's Gate-ym262.vgm"  ;- this song is so happy!!
+.binary "songs/02 At Doom's Gate-ym262.vgm"  ;- this song is so happy!!
 ;.binary "02 Character Select.vgm"

**Comment by dtremblay** [comment]
This issue has been fixed in the last update.
